services:
<<<<<<< HEAD

  apacheb1:
    build: ./apache
    container_name: apacheb1
    ports:
      - "6101:80"
    depends_on:
      - pythonb1

  pythonb1:
    build: .
    container_name: pythonb1
    env_file:
      - .env
    depends_on:
      - mariadbb1
    restart: unless-stopped

  mariadbb1:
    image: mariadb:11
    container_name: mariadbb1
    env_file:
      - .env
    volumes:
      - mariadb-datab1:/var/lib/mysql
      - ./01-rutinas.sql:/docker-entrypoint-initdb.d/01-rutinas.sql:ro
    restart: unless-stopped



  phpmyadminb1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminb1
    ports:
      - "7101:80"
    environment:
      PMA_HOST: mariadbb1
      PMA_PORT: 3306
    depends_on:
      - mariadbb1
    restart: unless-stopped


volumes:
  mariadb-datab1:
=======
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: ciber
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Chuches.sql://docker-entrypoint-initdb.d/Chuches.sql:ro
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  python:
    build: ./api
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: ciber
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb
  apache-waf:
    build: ./apache #./waf/ en un futuro
    ports:
      - 9090:80
    depends_on:
      - python
    links:
      - python
volumes:
  mariadb_data:
>>>>>>> d011334 (Test)
