apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: grupob1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.paths: /var/log/apache2/*.log        

        co.elastic.logs/module: apache
        co.elastic.logs.fileset.access.enabled: "true"
        co.elastic.logs.fileset.error.enabled: "true"
        co.elastic.logs/processors.add_fields.fields.service: apache-waf
        co.elastic.logs/processors.add_fields.fields.env: profesor
      labels:
        app: apache-waf
        env: grupob1
    spec:
      containers:
        - name: apache
          image: sirjousis/pepsapache:1.0
          ports:
            - containerPort: 80
